// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ckmqvrulxtkketqfqvdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrbXF2cnVseHRra2V0cWZxdmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODE4MzMsImV4cCI6MjA2MDA1NzgzM30.Ua1OPfxt83KvabLwA6-zFW0GBnG8i7WfSr-mD5dcZO4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);